apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-secret
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vaultwarden-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-token
      remoteRef:
        key: homelab/security/vaultwarden-secret
        property: admin-token
