apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: supabase-secret
    creationPolicy: Owner
  data:
    - secretKey: db-host
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: db-host
    - secretKey: db-port
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: db-port
    - secretKey: db-database
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: db-database
    - secretKey: db-password
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: db-password
    - secretKey: jwt-secret
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: jwt-secret
    - secretKey: anon-key
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: anon-key
    - secretKey: service-key
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: service-key
    - secretKey: realtime-secret-key-base
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: realtime-secret-key-base
    - secretKey: realtime-db-enc-key
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: realtime-db-enc-key
    - secretKey: meta-crypto-key
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: meta-crypto-key
    - secretKey: dashboard-username
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: dashboard-username
    - secretKey: dashboard-password
      remoteRef:
        key: homelab/supabase/supabase-secret
        property: dashboard-password
