apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: supabase-storage-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: supabase-storage-secret
    creationPolicy: Owner
  data:
    - secretKey: access-key-id
      remoteRef:
        key: homelab/supabase/supabase-storage-secret
        property: access-key-id
    - secretKey: secret-access-key
      remoteRef:
        key: homelab/supabase/supabase-storage-secret
        property: secret-access-key
