apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: homelab
  description: Homelab Kubernetes cluster and its deployed services
spec:
  owner: group:homelab
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: homelab
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: johannes
spec:
  memberOf: [homelab]
