apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: homelab/auth/keycloak-secret
        property: admin-password
