apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: infrastructure
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: minio-secret
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: homelab/infrastructure/minio
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: homelab/infrastructure/minio
        property: rootPassword
    - secretKey: storage-box-password
      remoteRef:
        key: homelab/infrastructure/minio
        property: storage-box-password
