apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-secret
  namespace: backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: velero-secret
    creationPolicy: Owner
  data:
    - secretKey: cloud
      remoteRef:
        key: homelab/backup/velero-secret
        property: cloud
