apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: minio
  description: S3-compatible object storage
  annotations:
    argocd/app-name: minio
    backstage.io/kubernetes-id: minio
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://minio-console.homelab.local
      title: MinIO Console
spec:
  type: service
  lifecycle: production
  owner: group:homelab
  system: homelab
