---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  children:
    server:
      hosts:
        k3s-server:
          ansible_host: 100.118.73.72
          k3s_role: server
          private_ip: 10.0.1.1
          location: cloud

    workers:
      hosts:
        k3s-worker-pi:
          ansible_host: 100.103.167.49
          ansible_user: ubuntu
          k3s_role: agent
          private_ip: 10.0.1.2
          location: home
        k3s-worker-minipc:
          ansible_host: 100.79.105.118
          ansible_user: ubuntu
          k3s_role: agent
          private_ip: 10.0.1.3
          location: home
