---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-modlist
  namespace: minecraft
data:
  modrinth-mods.txt: |
    # Automatisierung / Tech
    cc-tweaked:1.120.2
    advancedperipherals:1.20.1-0.7.48r
    mekanism:10.4.16.80
    mekanism-generators:10.4.16.80
    mekanism-tools:10.4.16.80
    ae2:15.3.6

    # Magie
    ars-nouveau:4.12.7
    botania:1.20.1-454-forge

    # Welt / Dimension
    forge:advanced-mining-dimension:forge-1.20.1-1.0.4
    terralith:2.5.4
    yungs-better-mineshafts:1.20-Forge-4.0.4

    # Ausruestung
    silent-gear:3.6.7

    # Vanilla+ Content
    farmers-delight:1.20.1-1.3.3
    quark:1.20.1-4.0-462
    supplementaries:1.20-3.1.43-forge
    sophisticated-storage:1.20.1-1.4.83.2111
    sophisticated-core:1.20.1-1.3.81.2280
    sophisticated-backpacks:1.20.1-3.24.67.2109
    pams-harvestcraft-2-food-core:1.0.5

    # Utility / QoL
    jei:15.56.0.205
    waystones:14.1.20+forge-1.20.1
    xaeros-minimap:forge-1.20.1-26.4.2
    xaeros-world-map:forge-1.20.1-1.46.0
    appleskin:2.5.1+mc1.20.1
    clumps:12.0.0.4
    mouse-tweaks:1.20.1-2.25.1-forge
    veinminer:1.1.0+mod
    simple-voice-chat:forge-1.20.1-2.6.22

    # Optimization
    entityculling:1.10.5
    ferrite-core:6.0.1
