---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-modlist
  namespace: minecraft
data:
  modrinth-mods.txt: |
    # Automatisierung / Tech
    cc-tweaked
    advancedperipherals
    mekanism:10.4.16.80
    mekanism-generators:10.4.16.80
    mekanism-tools:10.4.16.80
    ae2

    # Magie
    ars-nouveau
    botania

    # Welt / Dimension
    forge:advanced-mining-dimension:beta
    terralith
    yungs-better-mineshafts

    # Ausruestung
    silent-gear

    # Vanilla+ Content
    farmers-delight
    quark
    supplementaries
    sophisticated-storage:1.20.1-1.4.83.2111
    sophisticated-core:1.20.1-1.3.81.2280
    sophisticated-backpacks:1.20.1-3.24.67.2109

    # Utility / QoL
    jei:beta
    waystones
    xaeros-minimap
    appleskin
    clumps
    mouse-tweaks
    veinminer:1.1.0+mod

    # Optimization
    entityculling:1.10.5
    ferrite-core:6.0.1
