apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: backstage-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: homelab/backstage/backstage-secret
        property: db-password
    - secretKey: auth-session-secret
      remoteRef:
        key: homelab/backstage/backstage-secret
        property: auth-session-secret
    - secretKey: oidc-client-secret
      remoteRef:
        key: homelab/backstage/backstage-secret
        property: oidc-client-secret
    - secretKey: argocd-token
      remoteRef:
        key: homelab/backstage/backstage-secret
        property: argocd-token
