---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: overleaf-secrets
  namespace: overleaf
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: overleaf-secrets
    creationPolicy: Owner
  data:
    - secretKey: invite-token-secret
      remoteRef:
        key: homelab/overleaf/overleaf-secrets
        property: invite-token-secret
