apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-rails-secrets
  namespace: gitlab
spec:
  refreshInterval: 24h  # Rails Keys niemals rotieren solange GitLab läuft!
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: gitlab-rails-secrets
    creationPolicy: Owner
  data:
    - secretKey: secret_key_base
      remoteRef:
        key: homelab/gitlab/rails-secrets
        property: secret-key-base
    - secretKey: db_key_base
      remoteRef:
        key: homelab/gitlab/rails-secrets
        property: db-key-base
    - secretKey: otp_key_base
      remoteRef:
        key: homelab/gitlab/rails-secrets
        property: otp-key-base
    - secretKey: ci_job_token_signing_key
      remoteRef:
        key: homelab/gitlab/rails-secrets
        property: ci-job-token-signing-key
