apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-secret
  namespace: gitlab
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: gitlab-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: homelab/gitlab/gitlab-secret
        property: db-password
    - secretKey: redis-password
      remoteRef:
        key: homelab/gitlab/gitlab-secret
        property: redis-password
    - secretKey: oidc-client-secret
      remoteRef:
        key: homelab/gitlab/gitlab-secret
        property: oidc-client-secret
