apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alloy
  description: Log and metrics shipping agent (Grafana Alloy)
  annotations:
    argocd/app-name: alloy
    backstage.io/kubernetes-id: alloy
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:homelab
  system: homelab
