apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nextcloud-secret
    creationPolicy: Owner
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: homelab/productivity/nextcloud-secret
        property: nextcloud-username
    - secretKey: nextcloud-password
      remoteRef:
        key: homelab/productivity/nextcloud-secret
        property: nextcloud-password
    - secretKey: db-username
      remoteRef:
        key: homelab/productivity/nextcloud-secret
        property: db-username
    - secretKey: db-password
      remoteRef:
        key: homelab/productivity/nextcloud-secret
        property: db-password
    - secretKey: redis-password
      remoteRef:
        key: homelab/productivity/nextcloud-secret
        property: redis-password
    - secretKey: storage-box-password
      remoteRef:
        key: homelab/productivity/nextcloud-secret
        property: storage-box-password
    - secretKey: oidc-client-secret
      remoteRef:
        key: homelab/productivity/nextcloud-secret
        property: oidc-client-secret
