apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nocodb-secret
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: nocodb-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: homelab/productivity/nocodb-secret
        property: db-password
    - secretKey: db-url
      remoteRef:
        key: homelab/productivity/nocodb-secret
        property: db-url
    - secretKey: jwt-secret
      remoteRef:
        key: homelab/productivity/nocodb-secret
        property: jwt-secret
