apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secret
  namespace: productivity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: paperless-secret
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: db-username
    - secretKey: db-password
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: db-password
    - secretKey: redis-password
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: redis-password
    - secretKey: redis-url
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: redis-url
    - secretKey: secret-key
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: secret-key
    - secretKey: oidc-client-secret
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: oidc-client-secret
    - secretKey: smtp-username
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: smtp-username
    - secretKey: smtp-password
      remoteRef:
        key: homelab/productivity/paperless-secret
        property: smtp-password
